global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: [ ]
      scheme: http
      timeout: 10s
      api_version: v1

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - PROMETHUS_SERVER:9090

  - job_name: node-exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - SERVER_A:9100
          - SERVER_B:9100
          - SERVER_C:9100
          - SERVER_D:9100
          - SERVER_E:9100
          - SERVER_F:9100
          - SERVER_G:9100
          - SERVER_H:9100
    relabel_configs:
      - source_labels: [ __address__ ]
        regex: '(.*?)\..+'
        target_label: 'instance'
        replacement: '$1'

  - job_name: dcgm-exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - SERVER_A:9101
          - SERVER_B:9101
          - SERVER_C:9101
          - SERVER_D:9101
          - SERVER_E:9101
          - SERVER_F:9101
    relabel_configs:
      - source_labels: [ __address__ ]
        regex: '(.*?)\..+'
        target_label: 'instance'
        replacement: '$1'

  - job_name: cadvisor
    metrics_path: /metrics
    static_configs:
      - targets:
          - SERVER_A:9102
          - SERVER_B:9102
          - SERVER_C:9102
          - SERVER_D:9102
          - SERVER_E:9102
          - SERVER_F:9102
    relabel_configs:
      - source_labels: [ __address__ ]
        regex: '(.*?)\..+'
        target_label: 'instance'
        replacement: '$1'

  - job_name: pushgateway
    static_configs:
      - targets:
          - PUSHGATEWAY_SERVER:9091
    relabel_configs:
      - source_labels: [ __address__ ]
        regex: '(.*?)\..+'
        target_label: 'instance'
        replacement: '$1'
